package com.mygdx.alphabetizergame.Helpers;

import com.badlogic.gdx.Gdx;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Random;
import java.util.Set;

public class WordGenerator {

    List<String> generatedWords;
    List<List <String>> alphaList;
    List<String> deDuplicatedGeneratedWords;


    String[] Afourletterparted;
    String[] Bfourletterparted;
    String[] Cfourletterparted;
    String[] Dfourletterparted;
    String[] Efourletterparted;
    String[] Ffourletterparted;
    String[] Gfourletterparted;
    String[] Hfourletterparted;
    String[] Ifourletterparted;
    String[] Jfourletterparted;
    String[] Kfourletterparted;
    String[] Lfourletterparted;
    String[] Mfourletterparted;
    String[] Nfourletterparted;
    String[] Ofourletterparted;
    String[] Pfourletterparted;
    String[] Qfourletterparted;
    String[] Rfourletterparted;
    String[] Sfourletterparted;
    String[] Tfourletterparted;
    String[] Ufourletterparted;
    String[] Vfourletterparted;
    String[] Wfourletterparted;
    String[] Xfourletterparted;
    String[] Yfourletterparted;
    String[] Zfourletterparted;

    List<String> A4list;
    List<String> B4list;
    List<String> C4list;
    List<String> D4list;
    List<String> E4list;
    List<String> F4list;
    List<String> G4list;
    List<String> H4list;
    List<String> I4list;
    List<String> J4list;
    List<String> K4list;
    List<String> L4list;
    List<String> M4list;
    List<String> N4list;
    List<String> O4list;
    List<String> P4list;
    List<String> Q4list;
    List<String> R4list;
    List<String> S4list;
    List<String> T4list;
    List<String> U4list;
    List<String> V4list;
    List<String> W4list;
    List<String> X4list;
    List<String> Y4list;
    List<String> Z4list;


    public WordGenerator(){
        generatedWords = new ArrayList<String>();

        String AfourletterWords = "ABBA ABBE ABBR ABED ABET ABLE ABLY ABRA ABUT ACCT ACED ACES ACHE ACHY ACID ACLU ACME ACNE ACRE ACTS ADAM ADAR ADDS ADVT AFAR AFRO AGAR AGED AGES AGNI AGOG AGUE AHEM AHOY AIDE AIDS AILS AIMS AIRS AIRY AJAR AKIN ALAN ALAR ALAS ALBA ALBS ALES ALGA ALLY ALMA ALMS ALOE ALPS ALSO ALTO ALUM AMEN AMID AMMO AMOK AMPS ANDS ANET ANEW ANKH ANNA ANNE ANON ANSI ANTE ANTI ANTS ANUS APED APES APEX APSE AQUA ARAB ARCH ARCS AREA ARES ARGO ARIA ARID ARKS ARMS ARMY ARSE ARTS ARTY ARUM ASAP ASHY ASIA ASKS ASPS ASSN ASST ATOM ATOP ATTN ATTY AUBE AUKS AUNT AURA AUTO AVDP AVER AVES AVID AVIE AVIS AVOW AWAY AWED AWES AWLS AWNS AWOL AWRY AXED AXEL AXES AXIS AXLE AXON AYAH AYES";
        String BfourletterWords = "BAAL BAAS BABA BABE BABU BABY BACE BACH BACK BADE BADS BAFF BAFT BAGS BAHT BAIL BAIN BAIT BAKE BALD BALE BALI BALK BALL BALM BANC BAND BANE BANG BANK BANS BARB BARD BARE BARF BARK BARM BARN BARS BASE BASH BASK BASS BAST BATE BATH BATS BATZ BAUD BAUK BAWD BAWL BAWN BAYA BAYS BDRM BEAD BEAK BEAL BEAM BEAN BEAR BEAT BEAU BECK BEDE BEDS BEEF BEEM BEEN BEEP BEER BEES BEET BEGA BEGS BEHN BELK BELL BELT BEMA BEND BENE BENS BENT BERE BERG BERM BESS BEST BETA BETE BETS BEVY BEYS BIAS BIBB BIBS BICE BIDE BIDS BIER BIFF BIGA BIGG BIKE BIKH BILE BILK BILL BIND BINE BING BINK BINS BIOL BION BIOS BIRD BIRK BIRL BIRR BIRT BISE BISH BISK BITE BITO BITS BITT BLAB BLAE BLAH BLAT BLAY BLDG BLEA BLEB BLED BLEE BLEK BLET BLEW BLIN BLIP BLOB BLOC BLOT BLOW BLUB BLUE BLUR BLVD BOAR BOAS BOAT BOBS BOCA BOCE BOCK BODE BODS BODY BOER BOES BOFF BOGS BOGY BOIL BOKE BOLA BOLD BOLE BOLL BOLN BOLO BOLT BOMB BONA BOND BONE BONG BONO BONS BONY BOOB BOOK BOOM BOON BOOR BOOS BOOT BOPS BORD BORE BORN BORT BOSA BOSH BOSK BOSS BOTE BOTH BOTS BOUD BOUK BOUL BOUN BOUR BOUT BOWL BOWS BOXY BOYO BOYS BOZA BOZO BRAD BRAE BRAG BRAN BRAS BRAT BRAW BRAY BRED BREN BRET BREW BRID BRIE BRIG BRIM BRIN BRIO BRIT BROB BROG BROS BROW BRUH BRUN BRUT BUAT BUBO BUBS BUCK BUDS BUFF BUFO BUGS BUHL BULB BULK BULL BUMP BUMS BUND BUNG BUNK BUNN BUNS BUNT BUOY BURG BURH BURL BURN BURP BURR BURS BURT BURY BUSH BUSK BUSS BUST BUSY BUTS BUTT BUYS BUZZ BYES BYRE BYSS BYTE";
        String CfourletterWords = "CAAS CABS CACK CADE CADI CADS CADY CAFE CAGE CAGY CAKE CAKY CALC CALF CALI CALK CALL CALM CALX CAME CAMP CAMS CAND CANE CANS CANT CANY CAPE CAPS CARD CARE CARF CARK CARL CARP CARS CART CASA CASE CASH CASK CASS CAST CATA CATE CATS CAUF CAUK CAUL CAVE CAVY CAWK CAWS CAYO CAYS CECA CEDE CEES CEIL CELL CELT CENT CERE CERO CERT CESS CEST CETE CHAB CHAD CHAK CHAM CHAP CHAR CHAT CHAW CHEF CHEM CHES CHEW CHEZ CHIA CHIC CHID CHIN CHIP CHIT CHOP CHOU CHOW CHUB CHUD CHUG CHUM CIAO CILL CIMA CINE CION CIRC CIST CITE CITY CIVE CIZE CLAD CLAM CLAN CLAP CLAW CLAY CLEE CLEF CLEG CLEM CLEW CLIO CLIP CLOD CLOG CLOP CLOT CLOY CLUB CLUE CLUM CMDG COAG COAK COAL COAT COAX COBS COCA COCK COCO CODA CODE CODS COED COGS COHO COIF COIL COIN COIR COIT COKE COLA COLD COLE COLL COLP COLT COLY COMA COMB COME COMP COND CONE CONF CONG CONJ CONK CONN CONS CONT CONY COOK COOL COOM COON COOP COOS COOT COPE COPS COPY CORA CORB CORD CORE CORF CORK CORM CORN CORP COSH COSS COST COSY COTE COTS COUP COVE COWL COWS COXA COZY CRAB CRAG CRAM CRAN CRAP CRAW CRAY CREE CREW CRIB CRIC CROP CROW CRUD CRUP CRUS CRUT CRUX CTRL CUBA CUBE CUBS CUCA CUDS CUED CUES CUFF CUKE CULL CULM CULT CUND CUNT CUPS CURB CURD CURE CURL CURR CURS CURT CUSK CUSP CUSS CUTE CUTS CYAN CYMA CYME CYON CYST CZAR";
        String DfourletterWords = "DABB DABS DACE DADA DADE DADO DADS DAFF DAFT DAGO DAIS DALE DALF DAME DAMN DAMP DAMS DANA DANE DANG DANK DARE DARG DARK DARN DARR DART DASE DASH DATA DATE DAUB DAUK DAUN DAUW DAVE DAWE DAWK DAWN DAYS DAZE DBMS DEAD DEAF DEAL DEAN DEAR DEAS DEBS DEBT DECK DECO DEDE DEED DEEM DEEP DEER DEES DEEV DEFT DEFY DEGU DEIL DEIS DEJA DELE DELF DELI DELL DEME DEMI DEMO DEMY DENS DENT DENY DEPT DERE DERF DERK DERM DERN DESK DESS DEUS DEUX DEVA DEVE DEVI DEWS DEWY DEYE DEYS DHOW DIAG DIAL DIAM DIAN DIAS DIBS DICE DICH DICK DICT DIDO DIDY DIED DIEM DIES DIET DIGS DIKA DIKE DILL DIME DIMS DINE DING DINK DINS DINT DIPS DIPT DIRE DIRK DIRL DIRT DISC DISH DISK DITE DITT DIVA DIVE DIZZ DJIN DOAB DOAT DOCK DOCS DODD DODO DOER DOES DOFF DOGE DOGS DOGY DOIT DOJO DOKO DOLE DOLF DOLL DOLT DOME DOMS DONA DONE DONG DONI DONS DOOM DOOP DOOR DOPE DOPY DORM DORN DORP DORR DORS DORY DOSE DOSS DOST DOTE DOTH DOTS DOTY DOUC DOUR DOUT DOVE DOWL DOWN DOWS DOXY DOZE DOZY DRAB DRAD DRAG DRAM DRAT DRAW DRAY DREE DREG DREK DREW DREY DRIB DRIE DRIP DROH DROP DROW DRUB DRUG DRUM DRYS DUAD DUAL DUAN DUBB DUBS DUCE DUCK DUCT DUDE DUDS DUEL DUES DUET DUFF DUGS DUKE DULL DULY DUMB DUMP DUNE DUNG DUNK DUNS DUNT DUOS DUPE DURA DURE DURN DUSE DUSK DUST DUTY DYAD DYAS DYED DYER DYES DYKE DYNE";
        String EfourletterWords = "EACH EALE EAME EARL EARN EARS EASE EAST EASY EATH EATS EAUX EAVE EBBS EBON ECCL ECHE ECHO ECOL ECON ECRU ECUS EDAM EDDA EDDY EDEN EDGE EDGY EDIT EEKE EELS EELY EERY EFFS EFTS EGAD EGAL EGER EGGS EGIS EGOS EGRE EIGH EILD EIRE EJOO EKED EKES ELAN ELDS ELHI ELIX ELKE ELKS ELLS ELMS ELMY ELSE ELUL ELVE EMEU EMEW EMIR EMIT EMMY EMUS EMYD ENCL ENDS ENGR ENOW ENVY EONS EPEE EPEN EPHA EPIC EPOS ERAS ERAT ERGO ERGS ERIC ERIE ERIN ERKE ERME ERNE ERNS EROS ERRS ERSE ERSH ERST ESES ESOX ESPY ESSE ETCH ETHE ETNA ETUI ETYM EUGE EUGH EVAL EVEN EVER EVES EVET EVIL EWER EWES EWRY EXAM EXEC EXES EXIT EXON EXPO EYAS EYED EYEN EYER EYES EYET EYLE EYNE EYOT EYRA EYRE EYRY";
        String FfourletterWords = "FACE FACT FADE FADS FADY FAGS FAIL FAIN FAIR FAIT FAKE FALK FALL FALX FAME FAND FANE FANG FANS FARD FARE FARL FARM FARO FART FASH FAST FATE FATS FAUN FAUT FAUX FAWE FAWN FAYS FAZE FEAL FEAR FEAT FECK FEDS FEED FEEL FEES FEET FEHM FELE FELL FELT FEME FEND FENS FEOD FERE FERM FERN FERS FESS FEST FETA FETE FEUD FIAR FIAT FIBS FICA FICE FICO FIDE FIDO FIDS FIEF FIFE FIGS FIJI FIKE FILE FILL FILM FILS FIND FINE FINK FINN FINS FINT FIRE FIRK FIRM FIRS FISC FISH FISK FIST FITS FITT FITZ FIVE FIXE FIZZ FLAB FLAG FLAK FLAM FLAN FLAP FLAT FLAW FLAX FLAY FLEA FLED FLEE FLET FLEW FLEX FLIP FLIT FLIX FLOE FLOG FLON FLOP FLOW FLUB FLUE FLUS FLUX FOAL FOAM FOBS FOCI FOES FOGE FOGS FOGY FOIL FOIN FOLD FOLK FOND FONE FONT FOOD FOOL FOOT FOPS FORA FORD FORE FORK FORM FORT FOUL FOUR FOWL FOXY FOZY FRAB FRAG FRAP FRAT FRAU FRAY FRED FREE FREN FRET FRIG FRIM FRIT FRIZ FROE FROG FROM FROW FRUG FUAR FUBS FUCI FUCK FUDS FUEL FUFF FUGA FUGH FUGS FUJI FULL FUME FUMY FUND FUNK FURL FURS FURY FUSE FUSS FUST FUZE FUZZ FYKE FYRD";
        String GfourletterWords = "GABS GABY GADE GADS GAEL GAFF GAGA GAGE GAGS GAIN GAIT GALA GALE GALL GALS GALT GAME GAMP GAMS GAMY GANE GANG GAOL GAPE GAPS GAPY GARB GARD GARE GARS GARY GASH GASP GAST GATE GATS GAUD GAUL GAUR GAVE GAWK GAWN GAYS GAZE GEAL GEAN GEAR GEAT GECK GEDD GEED GEEK GEER GEES GEET GEEZ GEIC GEIN GELD GELS GELT GEMS GENA GENE GENS GENT GENU GEOG GEOL GEOM GERE GERM GERN GERY GEST GETH GETS GEUM GHAT GHEE GIBE GIBS GIDE GIFT GIGS GILA GILD GILE GILL GILT GIMP GING GINN GINS GIPS GIRD GIRE GIRL GIRN GIRT GISE GIST GITE GITH GIVE GLAD GLEE GLEG GLEN GLEW GLEY GLIB GLIM GLOB GLOM GLOP GLOW GLUE GLUM GLUT GLYN GNAR GNAT GNAW GNEW GNOF GNOW GNUS GOAD GOAF GOAL GOAR GOAT GOBS GOBY GODE GODS GOEL GOEN GOER GOES GOFF GOGO GOLD GOLF GOLL GOME GONE GONG GOOD GOOF GOOK GOON GOOP GOOS GOOT GORD GORE GORM GORY GOSH GOSS GOTE GOTH GOUD GOUR GOUT GOVE GOVT GOWD GOWK GOWL GOWN GOYS GRAB GRAD GRAF GRAM GRAS GRAY GREE GRES GRET GREW GREY GRID GRIG GRIL GRIM GRIN GRIP GRIS GRIT GROG GROS GROT GROW GRUB GRUF GRUM GUAM GUAN GUAR GUCK GUFF GUHR GUIB GUID GULA GULE GULF GULL GULP GULT GULY GUMP GUMS GUNA GUNG GUNK GUNS GURL GURT GURU GUSH GUST GUTS GUYS GUZE GYBE GYLE GYMS GYPS GYRE GYRI GYRO GYSE GYTE GYVE";
        String HfourletterWords = "HAAF HAAK HAAR HACK HADE HADJ HAFT HAGS HAHS HAIK HAIL HAIR HAJI HAJJ HAKE HALE HALF HALK HALL HALM HALO HALP HALS HALT HAME HAMS HAND HANG HANK HAPS HARD HARE HARK HARL HARM HARP HART HARY HASE HASH HASK HASP HAST HATE HATH HATS HAUL HAUM HAUT HAVE HAWK HAWM HAWS HAYE HAYS HAZE HAZY HEAD HEAL HEAM HEAP HEAR HEAT HEBE HECK HEED HEEL HEEP HEER HEFT HEIL HEIR HELD HELE HELL HELM HELP HEME HEMP HEMS HENG HENS HENT HERB HERD HERE HERL HERN HERO HERR HERS HERT HERY HESP HEST HETE HEUK HEWE HEWN HEWS HEXA HEYH HICK HIDE HIED HIES HIGH HIKE HILE HILL HILT HIND HINE HINK HINT HIPE HIPS HIRE HIRS HISN HISS HIST HITS HIVE HIZZ HOAR HOAX HOBO HOBS HOCK HODS HOED HOER HOES HOGH HOGO HOGS HOIT HOKE HOLD HOLE HOLM HOLP HOLT HOLY HOME HOMO HOMY HOND HONE HONG HONK HONT HOOD HOOF HOOK HOOL HOOM HOOP HOOT HOPE HOPI HOPS HORA HORE HORN HORS HOSE HOSP HOST HOTE HOTS HOUP HOUR HOVE HOWE HOWL HOWP HOWS HUBS HUCH HUCK HUED HUER HUES HUFF HUGE HUGS HUGY HUKE HULA HULK HULL HUMP HUMS HUNG HUNK HUNS HUNT HURL HURR HURT HUSH HUSK HUSO HUTS HUZZ HYDE HYEN HYKE HYMN HYNE HYPE HYPO";
        String IfourletterWords = "IAMB IBEX IBID IBIS ICBM ICED ICES ICKY ICON IDEA IDEE IDEM IDEO IDES IDLE IDLY IDOL IDYL IEEE IFFY IHVH IKON ILEX ILIA ILKE ILKS ILLS ILLY IMAM IMAN IMPI IMPS INCA INCE INCH INDE INEE INFO INIA INKS INKY INLY INNE INNS INRO INST INTL INTO INTR IONS IOTA IOWA IPSO IRAN IRAQ IRED IRES IRIS IRKS IRON IRPE ISIS ISLE ISMS ITAL ITCH ITEM ITER IUDS IWIS IXIA IZAR";
        String JfourletterWords = "JABS JACK JADE JAGG JAGS JAIL JAIN JAKE JAKO JAMB JAMS JANE JANT JAPE JARL JARS JASP JATO JAVA JAWN JAWS JAWY JAYS JAZZ JEAN JEAT JEEL JEEP JEER JEEZ JEFE JEHU JELL JERK JESS JEST JESU JETS JEUX JEWS JIBB JIBE JIBS JIFF JIGS JILL JILT JIMP JINK JINN JINS JINX JIVE JOBS JOCK JOES JOEY JOGS JOHN JOIE JOIN JOKE JOLE JOLL JOLT JOSE JOSH JOSO JOSS JOTA JOTS JOUK JOUL JOUR JOVE JOWL JOYS JUAN JUBA JUBE JUDO JUDY JUGA JUGE JUGS JUJU JUKE JULI JULY JUMP JUNE JUNK JUNO JUPE JURA JURE JURY JUST JUTE JUTS";
        String KfourletterWords = "KADI KAGE KAGU KAIL KAIN KAKA KALE KALI KAMA KAME KAMI KAND KARN KART KATE KAVA KAWN KAYO KAYS KECK KEEL KEEN KEEP KEGS KEIR KELD KELE KELL KELP KELT KEMB KEMP KENO KENS KENT KEPI KEPT KERB KERF KERL KERN KERS KESS KEST KETA KEYS KHAN KIBE KIBY KICK KIDS KIER KIEV KIKE KILL KILN KILO KILT KIND KINE KING KINK KINO KINS KIPE KIPS KIRK KISH KISS KIST KITE KITH KITS KIVA KIVE KIWI KNAB KNAG KNAP KNAR KNAW KNEE KNEW KNIT KNOB KNOP KNOR KNOT KNOW KNOX KNUR KOAN KOBA KOEL KOFF KOHL KOLA KONG KOOK KOTO KRIS KSAR KUDA KUDO KUDU KUNG KURD KWHR KYAR KYAT KYAW KYKE";
        String LfourletterWords = "LAAS LABS LACE LACK LACY LADE LADS LADY LAFT LAGS LAIC LAID LAIN LAIR LAIT LAKE LAKH LAKY LALO LAMA LAMB LAME LAMM LAMP LAMS LAND LANE LANG LANK LANT LAOS LAPP LAPS LARD LARE LARK LARS LARY LASH LASK LASS LAST LATA LATE LATH LAUD LAUS LAVA LAVE LAWE LAWM LAWN LAWS LAYS LAZE LAZY LEAD LEAF LEAK LEAL LEAM LEAN LEAP LEAR LEAS LEAT LECH LECT LEED LEEF LEEK LEEP LEER LEES LEET LEFT LEGE LEGS LEIS LEKS LEME LENA LEND LENE LENO LENS LENT LEOD LEON LEOS LERE LESE LESS LEST LETE LETS LEVA LEVE LEVI LEVO LEVY LEWD LEYS LIAR LIAS LIBS LICE LICH LICK LIDO LIDS LIED LIEF LIEN LIER LIES LIEU LIFE LIFT LIGE LIKE LILL LILT LILY LIMA LIMB LIME LIMN LIMO LIMP LIMU LIMY LIND LINE LING LINK LINO LINS LINT LINY LION LIPS LIRA LIRE LISP LISS LIST LITE LITH LITS LIVE LIXT LIZA LOAD LOAF LOAM LOAN LOBE LOBO LOBS LOCA LOCH LOCI LOCK LOCO LODE LOFT LOGE LOGO LOGS LOGY LOIN LOIR LOKE LOKI LOLL LOMA LOND LONE LONG LOOB LOOF LOOK LOOL LOOM LOON LOOP LOOS LOOT LOPE LOPS LORD LORE LORI LORN LORY LOSE LOSS LOST LOTE LOTH LOTO LOTS LOUD LOUK LOUP LOUR LOUT LOVE LOWH LOWK LOWN LOWS LUAU LUBE LUCE LUCK LUCY LUES LUFF LUGE LUGS LUKE LULL LULU LUMP LUNA LUNE LUNG LUNK LUNT LUNY LURE LURG LURK LUSH LUSK LUST LUTE LUTH LUXE LYAM LYES LYNE LYNX LYRA LYRE";
        String MfourletterWords = "MAAD MAAT MACE MACH MACK MACS MADE MADS MAGE MAGI MAGS MAHA MAIA MAID MAIL MAIM MAIN MAKE MAKI MALA MALE MALI MALL MALM MALT MAMA MAND MANE MANO MANS MANU MANX MANY MAPS MARA MARC MARE MARK MARL MARS MART MARX MARY MASE MASH MASK MASS MAST MATE MATH MATS MATT MATY MAUD MAUL MAUT MAWK MAWS MAXI MAYA MAYO MAYS MAZE MAZY MEAD MEAK MEAL MEAN MEAR MEAS MEAT MEAW MECH MEDE MEED MEEK MEER MEET MEGA MEIN MELD MELL MELT MEMO MEND MENS MENT MENU MEOW MERD MERE MERK MERL MERO MESA MESH MESS MEST META METE METH MEUM MEVE MEWL MEWS MIAS MIBS MICA MICE MICH MICK MICO MIDA MIDI MIDS MIEN MIFF MIGO MIGS MIKE MILD MILE MILK MILL MILS MILT MIME MINA MIND MINE MING MINI MINK MINS MINT MINX MINY MIRA MIRE MIRK MIRV MIRY MISC MISE MISO MISS MIST MISY MITE MITT MITU MITY MIXT MKTG MOAN MOAS MOAT MOBS MOCK MOCO MODE MODI MODO MODS MODY MOFF MOHA MOHO MOHR MOIL MOKE MOKY MOLA MOLD MOLE MOLL MOLT MOLY MOME MOMS MONA MONE MONK MONO MONS MONT MONY MOOD MOON MOOR MOOS MOOT MOPE MOPS MOPY MORA MORE MORN MORO MORT MOSK MOSS MOST MOTE MOTH MOTO MOTS MOUE MOUN MOVE MOWE MOWN MOWS MOXA MOYA MSEC MUCE MUCH MUCK MUDS MUFF MUGS MULE MULL MUMM MUMP MUMS MUND MUNG MUON MURE MURK MURR MUSA MUSE MUSH MUSK MUSS MUST MUTE MUTT MUXY MYNA MYTH MYXA";
        String NfourletterWords = "NABK NABS NAGS NAID NAIF NAIK NAIL NAIS NAKE NALE NALL NAME NAMO NAOS NAPE NAPS NAPU NARC NARD NARE NARK NART NARY NASA NASH NATH NATL NATO NAUT NAVE NAVY NAWL NAYS NAYT NAZE NAZI NEAF NEAL NEAP NEAR NEAT NEBS NECK NEED NEER NEIF NEMS NEON NEPA NERD NERE NERO NESE NESH NESS NEST NETS NEVE NEVI NEWS NEWT NEXT NIAS NIBS NICE NICK NIDE NIEF NIGH NILE NILL NILS NILT NIMS NINE NIPS NIPT NISI NITS NIXY NOAH NOBS NOCK NODE NODS NOEL NOES NOGS NOIE NOIL NOIR NOLE NOLL NOLO NOLT NOMA NOME NOMS NONE NOOK NOON NOOT NOPE NORM NORN NOSE NOSH NOST NOSY NOTA NOTE NOTS NOTT NOUN NOUS NOVA NOVO NOWD NOWS NOWT NUBS NUDE NUKE NULL NUMB NUNS NURL NUTS NYAS";
        String OfourletterWords = "OAFS OAKS OAKY OARS OARY OAST OATH OATS OBBE OBEY OBIS OBIT OBOE OBOL OCRA ODAL ODDS ODES ODIC ODIN ODOR ODYL OFAY OFFS OGAM OGEE OGLE OGRE OHED OHIO OHMS OILS OILY OINK OINT OKAY OKER OKIE OKRA OLAY OLDS OLEA OLEO OLES OLID OLIO OLLA OLPE OMEN OMER OMIT ONCE ONDE ONES ONLY ONTO ONUS ONYX OOHS OOPS OOZE OOZY OPAH OPAL OPEC OPEN OPES OPIE OPTS OPUS OPYE ORAL ORBS ORBY ORCA ORCH ORCS ORDO ORES ORFE ORGY ORIG ORLE ORLO ORTH ORTS ORYX OSAR OSLO OSSA OSSE OTIC OTIS OTTO OUCH OURS OUSE OUST OUTS OUZE OUZO OVAL OVEN OVER OVID OVUM OWCH OWED OWEL OWEN OWES OWLS OWNS OWRE OWSE OXEN OXES OXID OYER OYES OYEZ";
        String PfourletterWords = "PAAS PACA PACE PACK PACO PACS PACT PACU PADS PAGE PAHI PAID PAIL PAIN PAIR PAIS PALE PALI PALL PALM PALO PALP PALS PALY PANE PANG PANS PANT PAPA PAPE PAPS PARA PARD PARE PARK PARR PARS PART PASH PASK PASO PASS PAST PATE PATH PATS PAUL PAUM PAVE PAVO PAWK PAWL PAWN PAWS PAYN PAYS PEAG PEAK PEAL PEAN PEAR PEAS PEAT PEBA PECK PEDS PEED PEEK PEEL PEEN PEEP PEER PEES PEGM PEGS PEIN PEKE PELA PELF PELL PELT PEND PENK PENS PENT PEON PEPO PEPS PERE PERI PERK PERM PERN PERS PERT PERU PERY PESE PESO PEST PETS PEWS PHEW PHIZ PHYS PHYZ PIAL PIAN PICA PICE PICI PICK PICS PIED PIER PIES PIET PIGG PIGS PIKA PIKE PILE PILL PILY PIMA PIMP PINA PINE PING PINK PINS PINT PINY PION PIOT PIPA PIPE PIPS PIPY PIRL PIRN PISA PISE PISH PISS PIST PITA PITH PITS PITY PIUS PIXY PKWY PLAN PLAT PLAY PLEA PLED PLEY PLIM PLOC PLOD PLOP PLOT PLOW PLOY PLUG PLUM PLUS PNYX POAK POCK POCO PODS POEM POET POGY POKE POKY POLE POLK POLL POLO POLS POLT POLY POME POMP POND PONE PONG PONS PONY POOD POOH POOL POON POOP POOR POPE POPS PORE PORK PORN PORT PORY POSE POSH POSS POST POSY POTS POTT POUF POUP POUR POUT POWP POWS POZE PRAD PRAM PRAT PRAY PREP PRES PREY PRIE PRIG PRIM PRIS PRIX PROA PROC PROD PROF PROG PROM PRON PROP PROS PROW PROX PSST PUBS PUCE PUCK PUDS PUDU PUED PUER PUET PUFF PUGH PUGS PUIT PUKE PULE PULL PULP PULT PULU PUMA PUME PUMP PUMY PUNA PUNG PUNK PUNS PUNT PUNY PUOY PUPA PUPE PUPS PURE PURI PURL PURR PUSH PUSS PUTS PUTT PYET PYIN PYLA PYNE PYOT PYRE PYRO";
        String QfourletterWords = "QUIN QUIP QUIT QUIZ QUAY QUID";
        String RfourletterWords = "RACA RACE RACH RACK RACY RADE RADS RAFF RAFT RAGA RAGE RAGS RAIA RAID RAIL RAIN RAIP RAIS RAJA RAKE RAKI RALE RAMI RAMP RAMS RANA RAND RANG RANI RANK RANT RAPE RAPS RAPT RARA RARE RASE RASH RASP RATA RATE RATH RATS RAVE RAWS RAYS RAZE RAZZ RCPT READ REAK REAL REAM REAP REAR REBS RECD RECK RECS REDE REDO REDS REED REEF REEK REEL REEM REFS REFT REIF REIM REIN REIS REIT RELY REME REMS REND RENG RENO RENT REPS RESE RESP REST RETD RETE REVE REVS REWE REYN RHEA RHOB RHUS RIAL RIBS RICE RICH RICK RIDE RIDS RIEF RIEL RIFE RIFF RIFT RIGS RILE RILL RILY RIMA RIME RIMS RIMY RIND RINE RING RINK RIOT RIPE RIPS RISE RISH RISK RIST RITE RITZ RIVE ROAD ROAM ROAN ROAR ROBE ROBS ROCK ROCS RODE RODS RODY ROED ROES ROIL ROIN ROKE ROKY ROLE ROLL ROME ROMP ROMS RONG RONT ROOD ROOF ROOK ROOM ROON ROOP ROOT ROPE ROPY RORY ROSA ROSE ROSS ROST ROSY ROTA ROTE ROTO ROTS ROTY ROUE ROUK ROUN ROUP ROUT ROUX ROVE ROWN ROWS RUBE RUBS RUBY RUCK RUDD RUDE RUED RUER RUES RUFF RUFT RUGA RUGS RUIN RUKH RULE RULY RUMP RUMS RUNE RUNG RUNS RUNT RUSE RUSH RUSK RUSS RUST RUTH RUTS RYAL RYAS RYES RYND RYOT RYSH RYTH";
        String SfourletterWords = "SAAN SACK SACS SADH SADR SAFE SAGA SAGE SAGO SAGS SAGY SAIC SAID SAIL SAIM SAIN SAKE SAKI SALE SALM SALP SALT SAME SAMP SAND SANE SANG SANK SANS SAPS SARD SARI SARK SARN SART SASH SASS SATE SAUF SAUH SAUL SAUR SAUT SAVE SAWN SAWS SAYS SCAB SCAD SCAG SCAM SCAN SCAR SCAT SCIL SCOP SCOT SCOW SCRY SCUD SCUG SCUM SCUP SCUR SCUT SCYE SDAN SEAH SEAK SEAL SEAM SEAN SEAR SEAS SEAT SECK SECS SECT SEED SEEK SEEL SEEM SEEN SEEP SEER SEES SEET SEGO SEID SEKE SELD SELF SELL SELY SEME SEMI SEND SENS SENT SEPT SERA SERB SERE SERF SERR SESS SETA SETS SETT SEWE SEWN SEWS SEXT SEXY SEYE SEYH SHAB SHAD SHAG SHAH SHAM SHAT SHAW SHAY SHED SHES SHET SHEW SHIE SHIM SHIN SHIP SHIT SHIV SHMO SHOD SHOE SHOG SHOO SHOP SHOT SHOW SHUG SHUL SHUN SHUT SIAM SIBS SICE SICH SICK SICS SIDA SIDE SIFT SIGH SIGN SIKE SIKH SILE SILK SILL SILO SILT SIMA SIMP SINE SING SINH SINK SINS SIPE SIPS SIPY SIRE SIRS SIRT SISE SISS SIST SITE SITH SITS SITU SITZ SIVA SIZE SIZY SKAG SKAR SKAT SKEE SKEG SKEN SKEP SKEW SKID SKIM SKIN SKIP SKIS SKIT SKUA SKUE SKUN SKYS SLAB SLAG SLAM SLAP SLAT SLAV SLAW SLAY SLED SLEE SLEP SLEW SLEY SLID SLIK SLIM SLIP SLIT SLOB SLOE SLOG SLOO SLOP SLOT SLOW SLUB SLUE SLUG SLUM SLUR SLUT SMEE SMEW SMIT SMOG SMUG SMUT SNAG SNAP SNAR SNAW SNEB SNED SNET SNEW SNIB SNIG SNIP SNIT SNOB SNOD SNOT SNOW SNUB SNUG SOAK SOAL SOAM SOAP SOAR SOBS SOCK SODA SODS SOFA SOFI SOFT SOHO SOIL SOJA SOKE SOKO SOLA SOLD SOLE SOLI SOLO SOLY SOMA SOME SOND SONG SONS SOON SOOT SOPE SOPH SOPS SORA SORB SORD SORE SORI SORN SORS SORT SORY SOSS SOTE SOTS SOUL SOUN SOUP SOUR SOUS SOUT SOWL SOWN SOWS SOYA SOYS SPAD SPAE SPAN SPAR SPAS SPAT SPAW SPAY SPEC SPED SPER SPET SPEW SPIC SPIN SPIT SPOT SPRY SPUD SPUE SPUN SPUR SPUT STAB STAG STAL STAR STAT STAW STAY STED STEE STEG STEM STEP STET STEW STEY STIR STOA STOP STOR STOT STOW STRE STUB STUD STUM STUN STUT STYE STYX SUBS SUCH SUCK SUDD SUDS SUED SUER SUES SUET SUEY SUEZ SUFI SUIT SUJI SULA SULK SULL SULU SUMO SUMP SUMS SUNG SUNK SUNN SUNS SUPE SUPS SUPT SURA SURD SURE SURF SUSU SWAB SWAD SWAG SWAL SWAM SWAN SWAP SWAT SWAY SWIG SWIM SWOB SWOM SWOP SWUM SYCE SYKE SYLE SYNC SYNE SYRT SYTH";
        String TfourletterWords = "TABS TACK TACO TACT TADS TAEL TAEN TAGS TAHA TAHR TAIL TAIN TAIT TAKE TALC TALE TALI TALK TALL TAME TAMP TAMS TANA TANG TANK TANS TANT TAOS TAPA TAPE TAPS TARE TARN TARO TARP TARS TART TASK TASS TATE TATH TATS TATT TATU TAUR TAUT TAWS TAXI TBSP TEAD TEAK TEAL TEAM TEAR TEAS TEAT TECH TEDS TEED TEEK TEEL TEEM TEEN TEES TEIL TELL TEMP TEND TENE TENS TENT TERM TERN TERR TEST TETE TEUK TEXT THAI THAK THAN THAR THAT THAW THEA THEE THEM THEN THEW THEY THIN THIS THOR THOU THRO THRU THUD THUG THUS TIAR TICE TICK TICS TIDE TIDY TIED TIER TIES TIFF TIFT TIGH TIKE TILE TILL TILT TIME TIND TINE TING TINK TINS TINT TINY TIPI TIPS TIRE TIRL TIRO TITH TITI TITS TIVY TIZA TNPK TOAD TOAT TOBY TOCO TODY TOED TOES TOFF TOFT TOFU TOGA TOGO TOGS TOIL TOKE TOLA TOLD TOLE TOLL TOLT TOLU TOMB TOME TOMS TONE TONG TONS TONY TOOK TOOL TOOM TOON TOOT TOPE TOPH TOPI TOPS TORA TORC TORE TORI TORN TORO TORS TORT TORY TOSE TOSH TOSS TOST TOTA TOTE TOTO TOTS TOTY TOUR TOUT TOWN TOWS TOWY TOYS TOZE TOZY TRAD TRAM TRAP TRAY TREE TREF TREK TREN TRET TREW TREY TRIG TRIM TRIO TRIP TROD TRON TROP TROT TROW TROY TRUB TRUE TRUG TSAR TUBA TUBE TUBS TUCH TUCK TUET TUFA TUFF TUFT TUGS TULE TULL TUMP TUNA TUNE TUNK TUNS TUPI TUPS TURD TURF TURK TURM TURN TUSH TUSK TUTS TUTU TUUM TUZA TWAS TWAT TWAY TWEY TWIG TWIN TWIT TWOS TYDY TYER TYKE TYMP TYND TYNE TYNY TYPE TYPO TYRE TYRO TZAR";
        String UfourletterWords = "UDAL UFOS UGHS UGLI UGLY UKES ULAN ULNA ULVA UMBE UMBO UMPS UNAU UNBE UNCE UNCI UNCO UNDE UNDO UNDY UNIO UNIT UNIV UNIX UNKE UNTO UNTY UNUM UPAS UPON URAL URAO URBS URDS URDU UREA URGE URIC URIM URNS UROX URRY URSA URUS URVA USED USEE USER USES USSR UTAH UTAS UTES UTIA UTIS UTRO UVEA UVIC";
        String VfourletterWords = "VADE VAIL VAIN VAIR VALE VAMP VANE VANG VANS VANT VARA VARE VARI VARK VARY VASA VASE VAST VATS VAUT VEAL VEDA VEEP VEER VEES VEGA VEHM VEIL VEIN VELA VELD VELE VELL VENA VEND VENT VERB VERD VERS VERT VERY VESE VEST VETO VETS VIAL VIAS VICE VIDE VIED VIER VIES VIEW VILD VILE VILL VIMS VINA VINE VINO VINS VINY VIOL VIPS VIRE VISA VISE VITA VIVA VIVE VIVO VOCE VOID VOLE VOLT VOTE VOWS VROW VUGG VUGH VUGS VYCE";
        String WfourletterWords = "WAAG WACK WACS WADD WADE WADI WADS WADY WAEG WAFT WAGE WAGS WAID WAIF WAIL WAIN WAIR WAIT WAKE WAKF WALD WALE WALK WALL WALM WALT WALY WAMP WAND WANE WANG WANT WANY WAPP WARD WARE WARK WARM WARN WARP WARS WART WARY WASE WASH WASP WAST WATS WATT WAUL WAUR WAVE WAVY WAWE WAWL WAXY WAYK WAYS WEAK WEAL WEAN WEAR WEBS WEDS WEED WEEK WEEL WEEN WEEP WEET WEFT WEIR WEKA WELD WELE WELK WELL WELS WELT WEND WENE WENS WENT WEPT WERE WERK WERN WERT WESH WEST WETS WHAM WHAN WHAP WHAT WHEE WHEN WHET WHEW WHEY WHIG WHIM WHIN WHIP WHIR WHIT WHIZ WHOA WHOM WHOP WHOT WHUR WHYS WICH WICK WIDE WIER WIFE WIGG WIGS WIKE WILD WILE WILK WILL WILT WILY WIND WINE WING WINK WINO WINS WINY WIPE WIRE WIRY WISE WISH WISP WIST WITE WITH WITS WIVE WKLY WOAD WODE WOES WOKE WOKS WOLD WOLF WOLL WOMB WONE WONG WONT WOOD WOOF WOOK WOOL WOON WOOS WOPS WORD WORE WORK WORM WORN WORT WOST WOTS WOUL WOVE WOWE WOWF WOWS WRAP WRAW WRAY WREN WREY WRIE WRIG WRIT WULL WUST WYES WYKE WYLA WYND WYNN WYPE WYTE";
        String XfourletterWords = "XEME XIII XMAS XVII XXII XXIV XYST";
        String YfourletterWords = "YACK YAKS YALE YAMA YAMP YAMS YANG YANK YAPS YARD YARE YARK YARN YARR YATE YAUD YAUL YAUP YAWD YAWI YAWL YAWN YAWP YAWS YEAD YEAH YEAN YEAR YEAS YEDE YEEL YEGG YELK YELL YELP YEND YENS YERD YERK YERN YEST YETI YEVE YEWS YGHE YIDS YIFT YINS YIPE YIPS YITE YIVE YMCA YMEL YNOW YODE YOGA YOGI YOIT YOKE YOLD YOLK YOLL YOND YONI YORE YORK YOTE YOUL YOUR YOWE YOWL YOWS YREN YUAN YUCK YUEN YUGA YUKE YUKS YULE YUNX YURT YVEL YWAR YWCA YWIS";
        String ZfourletterWords = "ZAGS ZAIM ZAIN ZANY ZAPS ZARF ZATI ZEAL ZEBU ZEDS ZEES ZEIN ZEND ZERO ZEST ZETA ZEUS ZIGS ZIMB ZINC ZING ZINK ZION ZIPS ZOBO ZOEA ZOIC ZONA ZONE ZOOM ZOON ZOOS ZOPE ZORI ZUBR ZULU ZUNI ZYME";


        Afourletterparted = AfourletterWords.split(" ");
        Bfourletterparted = BfourletterWords.split(" ");
        Cfourletterparted = CfourletterWords.split(" ");
        Dfourletterparted = DfourletterWords.split(" ");
        Efourletterparted = EfourletterWords.split(" ");
        Ffourletterparted = FfourletterWords.split(" ");
        Gfourletterparted = GfourletterWords.split(" ");
        Hfourletterparted = HfourletterWords.split(" ");
        Ifourletterparted = IfourletterWords.split(" ");
        Jfourletterparted = JfourletterWords.split(" ");
        Kfourletterparted = KfourletterWords.split(" ");
        Lfourletterparted = LfourletterWords.split(" ");
        Mfourletterparted = MfourletterWords.split(" ");
        Nfourletterparted = NfourletterWords.split(" ");
        Ofourletterparted = OfourletterWords.split(" ");
        Pfourletterparted = PfourletterWords.split(" ");
        Qfourletterparted = QfourletterWords.split(" ");
        Rfourletterparted = RfourletterWords.split(" ");
        Sfourletterparted = SfourletterWords.split(" ");
        Tfourletterparted = TfourletterWords.split(" ");
        Ufourletterparted = UfourletterWords.split(" ");
        Vfourletterparted = VfourletterWords.split(" ");
        Wfourletterparted = WfourletterWords.split(" ");
        Xfourletterparted = XfourletterWords.split(" ");
        Yfourletterparted = YfourletterWords.split(" ");
        Zfourletterparted = ZfourletterWords.split(" ");



        A4list = new ArrayList<String>(Arrays.asList(Afourletterparted));
        B4list = new ArrayList<String>(Arrays.asList(Bfourletterparted));
        C4list = new ArrayList<String>(Arrays.asList(Cfourletterparted));
        D4list = new ArrayList<String>(Arrays.asList(Dfourletterparted));
        E4list = new ArrayList<String>(Arrays.asList(Efourletterparted));
        F4list = new ArrayList<String>(Arrays.asList(Ffourletterparted));
        G4list = new ArrayList<String>(Arrays.asList(Gfourletterparted));
        H4list = new ArrayList<String>(Arrays.asList(Hfourletterparted));
        I4list = new ArrayList<String>(Arrays.asList(Ifourletterparted));
        J4list = new ArrayList<String>(Arrays.asList(Jfourletterparted));
        K4list = new ArrayList<String>(Arrays.asList(Kfourletterparted));
        L4list = new ArrayList<String>(Arrays.asList(Lfourletterparted));
        M4list = new ArrayList<String>(Arrays.asList(Mfourletterparted));
        N4list = new ArrayList<String>(Arrays.asList(Nfourletterparted));
        O4list = new ArrayList<String>(Arrays.asList(Ofourletterparted));
        P4list = new ArrayList<String>(Arrays.asList(Pfourletterparted));
        Q4list = new ArrayList<String>(Arrays.asList(Qfourletterparted));
        R4list = new ArrayList<String>(Arrays.asList(Rfourletterparted));
        S4list = new ArrayList<String>(Arrays.asList(Sfourletterparted));
        T4list = new ArrayList<String>(Arrays.asList(Tfourletterparted));
        U4list = new ArrayList<String>(Arrays.asList(Ufourletterparted));
        V4list = new ArrayList<String>(Arrays.asList(Vfourletterparted));
        W4list = new ArrayList<String>(Arrays.asList(Wfourletterparted));
        X4list = new ArrayList<String>(Arrays.asList(Xfourletterparted));
        Y4list = new ArrayList<String>(Arrays.asList(Yfourletterparted));
        Z4list = new ArrayList<String>(Arrays.asList(Zfourletterparted));

        alphaList = new ArrayList<List<String>>(Arrays.asList(A4list, B4list, C4list, D4list, E4list, F4list, G4list, H4list, I4list, J4list, K4list, L4list, M4list, N4list, O4list, P4list, Q4list, R4list, S4list, T4list, U4list, V4list, W4list, X4list, Y4list, Z4list));

    }

    public void setGeneratedWordsFalling(){
        //get maximum of 3 random letters with maximum of 7 words per letter
        generatedWords.clear();

        int count;
        Random genRandom = new Random();
        int randomCount1 = genRandom.nextInt(7 - 1 + 1) + 1;
        int randomCount2 = genRandom.nextInt(7 - 1 + 1) + 1;

        int randomLetter1 = genRandom.nextInt((25 - 0) + 1) + 0;
        int randomLetter2 = genRandom.nextInt((25 - 0) + 1) + 0;
        int randomLetter3 = genRandom.nextInt((25 - 0) + 1) + 0;

        for(count = 0; count != randomCount1; count++){
            Collections.shuffle(alphaList.get(randomLetter1));
            generatedWords.add(alphaList.get(randomLetter1).get(0));
        }
        for(count = 0; count != randomCount2 && generatedWords.size() != 7; count++){
            Collections.shuffle(alphaList.get(randomLetter2));
            generatedWords.add(alphaList.get(randomLetter2).get(0));

        }
        //deDuplicatedGeneratedWords = new ArrayList<String>(new LinkedHashSet<String>(generatedWords));
        Set<String> set = new HashSet<String>(generatedWords);
        for (count = 0; set.size() != 7; count++) {
            Collections.shuffle(alphaList.get(randomLetter3));
            set.add(alphaList.get(randomLetter3).get(0));
        }
        deDuplicatedGeneratedWords = new ArrayList<String>(set);
        Gdx.app.log("fallinggenerator", "activated");

    }

    public void setGeneratedWordsTimer(){
        //get maximum of 7 random letters with maximum of 15 words per letter
        generatedWords.clear();

        int count;
        Random genRandom = new Random();
        int randomCount1 = genRandom.nextInt(15 - 1 + 1) + 1;
        int randomCount2 = genRandom.nextInt(15 - 1 + 1) + 1;
        int randomCount3 = genRandom.nextInt(15 - 1 + 1) + 1;
        int randomCount4 = genRandom.nextInt(15 - 1 + 1) + 1;
        int randomCount5 = genRandom.nextInt(15 - 1 + 1) + 1;
        int randomCount6 = genRandom.nextInt(15 - 1 + 1) + 1;

        int randomLetter1 = genRandom.nextInt((25 - 0) + 1) + 0;
        int randomLetter2 = genRandom.nextInt((25 - 0) + 1) + 0;
        int randomLetter3 = genRandom.nextInt((25 - 0) + 1) + 0;
        int randomLetter4 = genRandom.nextInt((25 - 0) + 1) + 0;
        int randomLetter5 = genRandom.nextInt((25 - 0) + 1) + 0;
        int randomLetter6 = genRandom.nextInt((25 - 0) + 1) + 0;
        int randomLetter7 = genRandom.nextInt((25 - 0) + 1) + 0;


        for(count = 0; count != randomCount1; count++){
            Collections.shuffle(alphaList.get(randomLetter1));
            generatedWords.add(alphaList.get(randomLetter1).get(0));
        }
        for(count = 0; count != randomCount2 && generatedWords.size() != 15; count++){
            Collections.shuffle(alphaList.get(randomLetter2));
            generatedWords.add(alphaList.get(randomLetter2).get(0));
        }
        for(count = 0; count != randomCount3 && generatedWords.size() != 15; count++){
            Collections.shuffle(alphaList.get(randomLetter3));
            generatedWords.add(alphaList.get(randomLetter3).get(0));
        }
        for(count = 0; count != randomCount4 && generatedWords.size() != 15; count++){
            Collections.shuffle(alphaList.get(randomLetter4));
            generatedWords.add(alphaList.get(randomLetter4).get(0));
        }
        for(count = 0; count != randomCount5 && generatedWords.size() != 15; count++){
            Collections.shuffle(alphaList.get(randomLetter5));
            generatedWords.add(alphaList.get(randomLetter5).get(0));
        }
        for(count = 0; count != randomCount6 && generatedWords.size() != 15; count++){
            Collections.shuffle(alphaList.get(randomLetter6));
            generatedWords.add(alphaList.get(randomLetter6).get(0));
        }

        //deDuplicatedGeneratedWords = new ArrayList<String>(new LinkedHashSet<String>(generatedWords));
        Set<String> set = new HashSet<String>(generatedWords);
        for (count = 0; set.size() != 15; count++) {
            Collections.shuffle(alphaList.get(randomLetter7));
            set.add(alphaList.get(randomLetter7).get(0));
        }
        deDuplicatedGeneratedWords = new ArrayList<String>(set);

    }

    public void setGeneratedWordsARS(){
        generatedWords.clear();
        Random genRandom = new Random();
        int randomLetter = genRandom.nextInt((25 - 0) + 1) + 0;
        Set<String> set = new HashSet<String>(generatedWords);
        for(int count = 0; count != 4 && set.size() != 4; count++){
            Collections.shuffle(alphaList.get(randomLetter));
            set.add(alphaList.get(randomLetter).get(0));
        }
        if(set.size() == 4){
        deDuplicatedGeneratedWords = new ArrayList<String>(set);
        }
        else {
           setGeneratedWordsARS();
        }
    }

    public List<String> getGeneratedWords(){
        return deDuplicatedGeneratedWords;
    }
}
